Update check-urls1.yml

diff --git a/.github/workflows/check-urls1.yml b/.github/workflows/check-urls1.yml
--- a/.github/workflows/check-urls1.yml
+++ b/.github/workflows/check-urls1.yml
@@ -13,6 +13,9 @@ jobs:
     steps:
       - name: URL Status Check
         run: |
+          # Fail script if an error is not handled explicitly
+          set -e
+          
           # Define an array of URLs to check
           urls=("https://www.swm.de/energiewende" "https://crm-m-waermepumpe.swm.de/web/login" "https://crm-m-waerme.swm.de/de/web/login" "https://nis-map-nahfw.apps.intra.swm.de")
 
@@ -24,7 +27,7 @@ jobs:
             echo "Checking URL: $url"
             
             # Make the GET request and capture the HTTP status code and any potential errors
-            status_code=$(curl -o /dev/null -s -w "%{http_code}" --connect-timeout 5 --max-time 10 "$url")
+            status_code=$(curl -o /dev/null -s -w "%{http_code}" --connect-timeout 5 --max-time 10 "$url" || true)
             
             # Capture the curl exit code
             curl_exit_code=$?
